//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int ProcedureID { get; set; }
        public int OfficeID { get; set; }
        public System.DateTime DateAndTime { get; set; }
        public string DescProvider { get; set; }
        public string DescCustomer { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Office Office { get; set; }
        public virtual Procedure Procedure { get; set; }
    }
}
